model_defaults: &model_defaults
  model_provider_url: "https://api.openai.com/v1"
  model: "gpt-4.1-mini"

game:
  map_name: standard_welfare
  seed: 0
  max_years: 10
  max_message_rounds: 2
wandb:
  disable: false
  run_name: null
  entity: alattar-ali-university-of-texas-at-austin
  project: wd_environment
  wandb_dir: './wandb_logs'
  save_code: false
logging:
  disable: false
  save_game: false
  log_level: INFO
  output_folder: games
players:
  ENGLAND:
    agent_class: PersonalityAgent
    agent_params:
      <<: *model_defaults
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      personality: "therapist"
  FRANCE:
    agent_class: PersonalityAgent
    agent_params:
      <<: *model_defaults
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
      personality: "therapist"
  ITALY:
    agent_class: PersonalityAgent
    agent_params:
      <<: *model_defaults
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
      personality: "therapist"
  GERMANY:
    agent_class: PersonalityAgent
    agent_params:
      <<: *model_defaults
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
      personality: "therapist"
  AUSTRIA:
    agent_class: PersonalityAgent
    agent_params:
      <<: *model_defaults
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
      personality: "therapist"
  RUSSIA:
    agent_class: PersonalityAgent
    agent_params:
      <<: *model_defaults
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
      personality: "therapist"
  TURKEY:
    agent_class: PersonalityAgent
    agent_params:
      <<: *model_defaults
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
      personality: "therapist"
