game:
  map_name: standard_welfare
  seed: 0
  max_years: 1
  max_message_rounds: 1
wandb:
  disable: false
  run_name: null
  entity: alattar-ali-university-of-texas-at-austin
  project: temporary
  wandb_dir: './wandb_logs'
  save_code: false
logging:
  disable: false
  save_game: false
  log_level: INFO
  output_folder: games
players:
  ENGLAND:
    agent_class: WdAgent
    agent_params:
      api_key: ollama
      model_provider_url: "http://localhost:12434/engines/llama.cpp/v1/"
      model: "ai/llama3.2"
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
  FRANCE:
    agent_class: WdAgent
    agent_params:
      api_key: ollama
      model_provider_url: "http://localhost:12434/engines/llama.cpp/v1/"
      model: "ai/llama3.2"
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
  ITALY:
    agent_class: WdAgent
    agent_params:
      api_key: ollama
      model_provider_url: "http://localhost:12434/engines/llama.cpp/v1/"
      model: "ai/llama3.2"
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
  GERMANY:
    agent_class: WdAgent
    agent_params:
      api_key: ollama
      model_provider_url: "http://localhost:12434/engines/llama.cpp/v1/"
      model: "ai/llama3.2"
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
  AUSTRIA:
    agent_class: WdAgent
    agent_params:
      api_key: ollama
      model_provider_url: "http://localhost:12434/engines/llama.cpp/v1/"
      model: "ai/llama3.2"
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
  RUSSIA:
    agent_class: WdAgent
    agent_params:
      api_key: ollama
      model_provider_url: "http://localhost:12434/engines/llama.cpp/v1/"
      model: "ai/llama3.2"
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
  TURKEY:
    agent_class: WdAgent
    agent_params:
      api_key: ollama
      model_provider_url: "http://localhost:12434/engines/llama.cpp/v1/"
      model: "ai/llama3.2"
      temperature: 1
      top_p: 0.9
      max_completion_errors: 30
      max_message_rounds: 3
